language: python

#python:
# - "3"

# virtualenv:
#   system_site_packages: true

before_install:
  - python3 -m venv venv
  - . venv/bin/activate

install:
  - pip install -r requirements.txt


script:
  - test.py
  - pylint main.py
